%obtain proposals
load('datamatchsearchstop.mat'); %load the dataset, see an example in the 'LBA_Forstmann_scanner.mat' 
load('LBA_matchsearchstop_covariance_popOut.mat');
num_subjects=length(data.rt); %number of subjects in the experiments
for j=1:num_subjects
    num_trials(j,1)=length(data.rt{j,1}); %computing the number of trials per subject
end
burn=1000;% the burn in iterations
adapt=5000;
nit=10000; % we take the last 10000 draws out of 12000 draws
length_draws=length(theta_mu_store);
for j=1:num_subjects 
      theta=[theta_latent_b10_store(length_draws-(adapt-1):length_draws,j),theta_latent_b20_store(length_draws-(adapt-1):length_draws,j),theta_latent_b30_store(length_draws-(adapt-1):length_draws,j),theta_latent_A0_store(length_draws-(adapt-1):length_draws,j),...
             theta_latent_v10_store(length_draws-(adapt-1):length_draws,j),theta_latent_v210_store(length_draws-(adapt-1):length_draws,j),theta_latent_v220_store(length_draws-(adapt-1):length_draws,j),theta_latent_v230_store(length_draws-(adapt-1):length_draws,j),theta_latent_tau0_store(length_draws-(adapt-1):length_draws,j),...
             theta_latent_b11_store(length_draws-(adapt-1):length_draws,j),theta_latent_b21_store(length_draws-(adapt-1):length_draws,j),theta_latent_b31_store(length_draws-(adapt-1):length_draws,j),theta_latent_A1_store(length_draws-(adapt-1):length_draws,j),...
             theta_latent_v11_store(length_draws-(adapt-1):length_draws,j),theta_latent_v211_store(length_draws-(adapt-1):length_draws,j),theta_latent_v221_store(length_draws-(adapt-1):length_draws,j),theta_latent_v231_store(length_draws-(adapt-1):length_draws,j),theta_latent_tau1_store(length_draws-(adapt-1):length_draws,j),...
             theta_latent_b12_store(length_draws-(adapt-1):length_draws,j),theta_latent_b22_store(length_draws-(adapt-1):length_draws,j),theta_latent_b32_store(length_draws-(adapt-1):length_draws,j),theta_latent_A2_store(length_draws-(adapt-1):length_draws,j),...
             theta_latent_v12_store(length_draws-(adapt-1):length_draws,j),theta_latent_v212_store(length_draws-(adapt-1):length_draws,j),theta_latent_v222_store(length_draws-(adapt-1):length_draws,j),...
             theta_latent_v232_store(length_draws-(adapt-1):length_draws,j),theta_latent_tau2_store(length_draws-(adapt-1):length_draws,j),...
             theta_mu_store(length_draws-(adapt-1):length_draws,:),chol_theta_sig2_store1(length_draws-(adapt-1):length_draws,:),chol_theta_sig2_store2(length_draws-(adapt-1):length_draws,:),chol_theta_sig2_store3(length_draws-(adapt-1):length_draws,:),chol_theta_sig2_store4(length_draws-(adapt-1):length_draws,:),chol_theta_sig2_store5(length_draws-(adapt-1):length_draws,:),...
             chol_theta_sig2_store6(length_draws-(adapt-1):length_draws,:),chol_theta_sig2_store7(length_draws-(adapt-1):length_draws,:),chol_theta_sig2_store8(length_draws-(adapt-1):length_draws,:),...
             chol_theta_sig2_store9(length_draws-(adapt-1):length_draws,:),chol_theta_sig2_store10(length_draws-(adapt-1):length_draws,:),chol_theta_sig2_store11(length_draws-(adapt-1):length_draws,:),...
             chol_theta_sig2_store12(length_draws-(adapt-1):length_draws,:),chol_theta_sig2_store13(length_draws-(adapt-1):length_draws,:),chol_theta_sig2_store14(length_draws-(adapt-1):length_draws,:),...
             chol_theta_sig2_store15(length_draws-(adapt-1):length_draws,:),chol_theta_sig2_store16(length_draws-(adapt-1):length_draws,:),chol_theta_sig2_store17(length_draws-(adapt-1):length_draws,:),chol_theta_sig2_store18(length_draws-(adapt-1):length_draws,:),...
             chol_theta_sig2_store19(length_draws-(adapt-1):length_draws,:),chol_theta_sig2_store20(length_draws-(adapt-1):length_draws,:),chol_theta_sig2_store21(length_draws-(adapt-1):length_draws,:),...
             chol_theta_sig2_store22(length_draws-(adapt-1):length_draws,:),chol_theta_sig2_store23(length_draws-(adapt-1):length_draws,:),chol_theta_sig2_store24(length_draws-(adapt-1):length_draws,:),...
             chol_theta_sig2_store25(length_draws-(adapt-1):length_draws,:),chol_theta_sig2_store26(length_draws-(adapt-1):length_draws,:),chol_theta_sig2_store27(length_draws-(adapt-1):length_draws,:)];
             % in the matrix called theta above, you have to list 
             % (1) all your random effects in the LBA model,(2) followed by the parameters \mu_{\alpha}, and
             % cholesky factor (lower triangular matrix) of the covariance
             % matrix \Sigma_{\alpha}
             covmat_theta(:,:,j)=cov(theta); %computing sample covariance matrix for the joint random effects and parameters \mu_{\alpha} and \Sigma_{\alpha}
             covmat_theta(:,:,j)=topdm(covmat_theta(:,:,j)); %little correction if the covariance matrix for the proposal is not positive definite matrix.
             mean_theta(j,:)=mean(theta); %computing the sample mean for the joint random effects and parameters \mu_{\alpha} and \Sigma_{\alpha}
end     

